cmake_minimum_required(VERSION 3.0.0)
project(SoulSphereEngine VERSION 0.1.0 LANGUAGES CXX)

# SoulSphereEngine variables
set(SS_ENGINE_NAME "SoulSphereEngine")
set(SS_ENGINE_SHORT_NAME "SSEngine")
set(SS_ENGINE_DIR ${CMAKE_CURRENT_LIST_DIR})
set(SS_ENGINE_INCLUDE_DIR ${SS_ENGINE_DIR}/include)
set(SS_ENGINE_SOURCE_DIR ${SS_ENGINE_DIR}/src)
set(SS_ENGINE_TESTS_DIR ${SS_ENGINE_DIR}/tests)
set(SS_ENGINE_DOCS_DIR ${SS_ENGINE_DIR}/docs)
set(SS_ENGINE_BIN_DIR ${SS_ENGINE_DIR}/bin)
set(SS_ENGINE_OBJ_DIR ${SS_ENGINE_DIR}/bin-int)
set(SS_ENGINE_VENDOR_DIR ${SS_ENGINE_DIR}/vendor)
set(SS_ENGINE_LIB_TYPE "SHARED")

file(GLOB_RECURSE SS_ENGINE_SOURCES ${SS_ENGINE_SOURCE_DIR}/*.cpp)
file(GLOB_RECURSE SS_ENGINE_HEADERS ${SS_ENGINE_SOURCE_DIR}/*.hpp)
file(GLOB_RECURSE SS_ENGINE_HEADERS ${SS_ENGINE_INCLUDE_DIR}/*.hpp ${SS_ENGINE_HEADERS})

# SoulSphereEngine library
add_library(${SS_ENGINE_NAME} ${SS_ENGINE_LIB_TYPE}
    ${SS_ENGINE_SOURCES} ${SS_ENGINE_HEADERS})

# SoulSphereEngine properties
target_include_directories(${SS_ENGINE_NAME} PUBLIC ${SS_ENGINE_INCLUDE_DIR})
set_property(TARGET ${SS_ENGINE_NAME} PROPERTY LINKER_LANGUAGE CXX)
set_property(TARGET ${SS_ENGINE_NAME} PROPERTY CXX_STANDARD 23)